spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #    url: ${MYSQL_CONNECTION_STRING}
    url: jdbc:mysql://${MYSQL_SERVER}:${MYSQL_SERVER_PORT}/${BFF_DB_NAME}?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  logging:
    level:
      org.springframework.security=DEBUG
server:
  port: ${BFF_PORT}
jwt-secret: SkzL9DNlghANAvjcxxKtSiwENSPYwbbI

STORAGE_CLIENT_NAME: ${STORAGE_CLIENT_NAME}
STORAGE_PORT: ${STORAGE_PORT}
ZOOSTORE_CLIENT_NAME: ${ZOOSTORE_CLIENT_NAME}
ZOOSTORE_PORT: ${ZOOSTORE_PORT}